#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OUTPUT_FILE="${1:-${SCRIPT_DIR}/.deploy-info}"

git_value() {
  local repo_path="$1"
  shift

  git -C "${repo_path}" "$@" 2>/dev/null || true
}

write_var() {
  local key="$1"
  local value="$2"
  printf '%s=%q\n' "${key}" "${value}"
}

write_repo_metadata() {
  local prefix="$1"
  local repo_path="$2"
  local ref subject branch full_sha

  ref="$(git_value "${repo_path}" rev-parse --short HEAD)"
  full_sha="$(git_value "${repo_path}" rev-parse HEAD)"
  subject="$(git_value "${repo_path}" log -1 --pretty=%s)"
  branch="$(git_value "${repo_path}" branch --show-current)"

  write_var "${prefix}REF" "${ref:-unknown}"
  write_var "${prefix}SHA" "${full_sha:-unknown}"
  write_var "${prefix}COMMIT_SUBJECT" "${subject:-unknown}"
  write_var "${prefix}BRANCH" "${branch:-detached}"
}

{
  printf '# Generated by deploy/production/write-deploy-info.sh; safe to rsync, do not edit by hand.\n'
  write_repo_metadata "DEPLOY_" "${REPO_ROOT}"
  write_repo_metadata "DEPLOY_FRONTEND_" "${REPO_ROOT}/frontend"
  write_repo_metadata "DEPLOY_BACKEND_" "${REPO_ROOT}/backend"
  write_var "DEPLOY_GENERATED_AT" "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
} >"${OUTPUT_FILE}"
